### ISSUE TITLE
Connect to IDRAC

### ISSUE THREAD

**Issue by coding-to-music** [zimmertr/TKS-Bootstrap_Proxmox#10]
My use case would be setting this up on Digitalocean (at least to do Hello World)

Then perhaps set up a dedicated server

So the "Connect to IDRAC" - how do I move forward? Do I need a physical bare metal server or can I use a generic droplet?

**Comment by zimmertr** [comment]
Only Proxmox is supported at this time. You can likely salvage a lot of the Ansible to create your own DO solution. PRs are welcome :)
