### ISSUE TITLE
ZFS_POOL_LIST missing from documentation

### ISSUE THREAD

**Issue by baodrate** [zimmertr/TKS-Bootstrap_Proxmox#2]
`TKS_BP_V_ZFS_POOL_LIST` is specified in `Ansible/site.yml` and used in `Ansible/roles/Configure_Proxmox/tasks/configure_zfs.yml` but isn't described in the readme

:)

**Comment by zimmertr** [comment]
Hi, thanks for opening this (and the other) issue! I have to admit I haven't went through and polished this project up just yet as you have noticed. This is an ongoing refactor so things are going to be chaotic for a while. I basically wrote all of this while rebuilding my lab on new hardware this summer. 

I would be very interested in hearing more about your experience using all of this. I'd be happy to answer any questions about getting it up and running if you have them too. I'm specifically interested in hearing how your different hardware impacts the scripts and seeing how you solve that as well as what your eventual Kustomize overlays look like.

As for this issue specifically, I'll try and patch things up when I get some free time this week. 

Thanks again!

**Comment by baodrate** [comment]
No problem, thanks for writing all this out. This is more organized and documented than I would've done, so I really appreciate you putting in the work. It's especially useful because I was trying to figure out how to get kubernetes deployed on my home setup and I noticed you had literally just [deprecated the other project](https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU). Took that as a sign I should give this one a shot (:

I'm honestly very impressed how neatly laid out everything is so far. I haven't done a lot of ansible so huge thanks for making everything easy to navigate and understand. There's only been a few small things that have tripped me up so far. Since I'm going through this step-by-step to get it working, I figure it'll be easier for me to debug/proofread things as I go along. I can make some PRs for the things I find, if you don't mind?

**Comment by zimmertr** [comment]
Yes please! That would be very much appreciated.

**Comment by zimmertr** [comment]
Went ahead and reviewed and merged all of your changes today, thanks again. Have you had a change to[ deploy Kubernetes](https://github.com/zimmertr/TKS-Bootstrap_Kubernetes) with the tooling yet?
